"""
This is a setup.py script originally generated by py2applet. It is ONLY 
good for building a Mac OS X applet bundle.

Usage:
    python setup.py py2app
"""

from setuptools import setup

VER = '0.27.0'
APP = ['Network Remote.pyw']
DATA_FILES = ['Network Remote.help']
PLIST = {'CFBundleVersion': VER, 'CFBundleShortVersionString': VER,
         'CFBundleIdentifier': 'com.wmcbrine.NetworkRemote',
         'CFBundleHelpBookFolder': 'Network Remote.help',
         'CFBundleHelpBookName': 'Network Remote Help',
         'NSHumanReadableCopyright': '2008-2013 William McBrine'}
OPTIONS = {'includes': 'Zeroconf', 'semi_standalone': True,
           'site_packages': True, 'argv_emulation': True,
           'argv_inject': ['-g'], 'plist': PLIST,
           'iconfile': 'Network Remote.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
